### ISSUE TITLE
Dockerfile request.

### ISSUE THREAD

**Issue by Sdgr90** [riblidezso/unique_mutation#1]
Hi 
We want to try to use Isomut on CGC genomics clouds, to do that it's necessary a docker containing isomut.
Can you please provide it?
Thanks very much in advance.

**Comment by riblidezso** [comment]
Hi, 

I think we can do that. Please specify how its should work. Inputs/outputs etc.
Also please redirect your question to the offficial repo, https://github.com/genomicshu/isomut

Thanks
Dezso
